# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
#        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: show env
      run: >
        echo "github.ref=${{ github.ref }}
        echo "github.event_name=${{ github.event_name }}

    - name: Build with Maven
      if: success() && github.event_name == 'pull_request'
      run: mvn -B verify

    - name: Publish to GitHub Packages
      if: success() && github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
      run: mvn -B clean install sonar:sonar site site-deploy -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

#    - name: Set up JDK 17
#      uses: actions/setup-java@v3
#      with:
#        java-version: '17'
#        distribution: 'temurin'
#        cache: 'maven'
#        server-id: sonatype-nexus-snapshots
#        server-username: SONATYPE_USERNAME
#        server-password: SONATYPE_PASSWORD
#        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
#        gpg-passphrase: SONATYPE_GPG_PASSPHRASE
#        settings-path: ${{ github.workspace }} # location for the settings.xml file

#    - name: Publish to Sonatype OSS
#      run: mvn deploy
#      env:
#        MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
#        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
#        SONATYPE_GPG_PASSPHRASE: ${{ secrets.SONATYPE_GPG_PASSPHRASE }}